apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e2jn5j4l6-dotnet-basic
  janus-idp.io/tekton: e2jn5j4l6-dotnet-basic
  backstage.io/kubernetes-id: e2jn5j4l6-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e2jn5j4l6-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
