apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e2jn5j4l6-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/e2jn5j4l6-dotnet-basic-gitops